<?php

namespace Ort\IotBundle\Repository;

/**
 * IoTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IoTRepository extends \Doctrine\ORM\EntityRepository
{
}
